### ISSUE TITLE
dso_dataset exception on mac

### ISSUE THREAD

**Issue by hlzz** [JakobEngel/dso#6]
I previously submitted a patch for dso to work on mac. The build went smoothly and I've got impressive results on a linux machine. But it turned out that dso_dataset cannot run on mac. The following log messages are given for your reference:

Tianweis-Macbook:bin STW$ ./dso_dataset files=/Users/STW/Downloads/sequence_38/images calib=/Users/STW/Downloads/sequence_38/camera.txt gamma=/Users/STW/Downloads/sequence_38/pcalib.txt vignette=/Users/STW/Downloads/sequence_38/vignette.png preset=0 mode=0
loading data from /Users/STW/Downloads/sequence_38/images!
loading calibration from /Users/STW/Downloads/sequence_38/camera.txt!
loading gammaCalib from /Users/STW/Downloads/sequence_38/pcalib.txt!
loading vignette from /Users/STW/Downloads/sequence_38/vignette.png!

=============== PRESET Settings: ===============
DEFAULT settings:
- no  real-time enforcing
- 2000 active points
- 5-7 active frames
- 1-6 LM iteration each KF
- original image resolution
==============================================
PHOTOMETRIC MODE WITH CALIBRATION!
Reading Calibration from file /Users/STW/Downloads/sequence_38/camera.txt ... found!
found ATAN camera model, building rectifier.
Input resolution: 1280 1024
In: 0.535719 0.669567 0.493249 0.500409 0.897966
Out: Crop
Output resolution: 640 480
finding CROP optimal new model!
initial range: x: -1.1372 - 1.1901; y: -0.8311 - 0.8292!
iteration 00001: range: x: -1.1315 - 1.1841; y: -0.8311 - 0.8292!
iteration 00002: range: x: -1.1258 - 1.1782; y: -0.8311 - 0.8292!
iteration 00003: range: x: -1.1258 - 1.1782; y: -0.8270 - 0.8251!
iteration 00004: range: x: -1.1258 - 1.1782; y: -0.8228 - 0.8209!
iteration 00005: range: x: -1.1258 - 1.1782; y: -0.8228 - 0.8209!

Rectified Kamera Matrix:
 277.34       0 312.234
      0 291.402 239.777
      0       0       1

Reading Photometric Calibration from file /Users/STW/Downloads/sequence_38/pcalib.txt
Reading Vignette Image from /Users/STW/Downloads/sequence_38/vignette.png
Successfully read photometric calibration!
got 3330 images and 3330 timestamps and 3330 exposures.!
ImageFolderReader: got 3330 files in /Users/STW/Downloads/sequence_38/images!
using pyramid levels 0 to 3. coarsest resolution: 80 x 60!
START PANGOLIN!
2016-11-15 15:09:17.588 dso_dataset[34151:3705298] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fffc56316fb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fffd9e38a2a objc_exception_throw + 48
	2   AppKit                              0x00007fffc394450c -[NSApplication(NSEvent) shouldBeTreatedAsInkEvent:] + 0
	3   libpangolin.dylib                   0x000000010d6d737f -[PangolinNSApplication run_step] + 79
	4   libpangolin.dylib                   0x000000010d6d6d7c _ZN8pangolin9OsxWindowC2ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEiib + 300
	5   libpangolin.dylib                   0x000000010d6d6b80 _ZN8pangolin19CreateWindowAndBindENSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEiiRKNS_6ParamsE + 384
	6   dso_dataset                         0x000000010d55f4d5 _ZN3dso6IOWrap17PangolinDSOViewer3runEv + 133
	7   libboost_thread-mt.dylib            0x000000010d611c14 _ZN5boost12_GLOBAL__N_112thread_proxyEPv + 164
	8   libsystem_pthread.dylib             0x00007fffda92caab _pthread_body + 180
	9   libsystem_pthread.dylib             0x00007fffda92c9f7 _pthread_body + 0
	10  libsystem_pthread.dylib             0x00007fffda92c221 thread_start + 13
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

It seems that the problem involves pangolin. Any idea how to fix it?

**Comment by JakobEngel** [comment]
Humm, yes, that seems like a Pangolin issue (or an issue with how I'm using it).

**Comment by sunstarchan** [comment]
@JakobEngel I've waiting for a long time to see you publish the DSO code. Thanks a lot. 


I also run into this problem. And the root cause is that OpenCV windows for display internal result must be the main thread. As you can see the error information: reason: 'nextEventMatchingMask should only be called from the Main Thread!'

I also reported this problem to OpenCV. The comment from them is 

    Looks like you use Cocoa window backend, there could be problems when working with windows and views from different threads: [Thread Safety Summary](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/Multithreading/ThreadSafetySummary/ThreadSafetySummary.html)

    I have doubts that thread-safe window handling can be implemented within current highgui interface using [Cocoa backend](https://github.com/Itseez/opencv/blob/master/modules/highgui/src/window_cocoa.mm). If you have different opinion - feel free to post your thoughts here.

    You can also try to use [Qt backend](https://github.com/Itseez/opencv/blob/master/modules/highgui/src/window_QT.cpp) (build OpenCV with Qt support), it should support working with windows from threads other than main.

https://github.com/opencv/opencv/issues/6039#issuecomment-181359159


And I also meet this issue when running ORB_SLAM, after I move the cv::imshow to main thread, the crash goes away. So in order to run on Mac, we should move the display into main thread.

**Comment by JakobEngel** [comment]
I'm actually not using openCV for visualization (at least not per default), exactly because I kept getting issues reported due to those threading issues. the problem is likely the same though:

Apparently MacOS requires all rendering / GUI-related functions to be called not only from *the same* thread (which I believe I'm doing), but needs them to be called from *the main* thread of the process. I will have a look if there is an elegant way of solving that (essentially moving the main(...) stuff into a dedicated thread, and call PangolinDSOViewer::run() from the processes main thread) - although that is somewhat ugly.
In the meantime, a (non-ideal) workaround should be to disable the GUI (-nogui).

Also, If anyone knows of a fix to Pangolin that will allow it to open a window & render stuff from a non-main-thread (which I believe should be possible on MacOS), please let me know!

**Comment by lukasvst** [comment]
I also ran into this issue a few weeks ago and moving the GUI part into the main thread solved the issue.
While it messes up the code structure a little bit it does not take long to implement it and since then DSO runs perfectly on Mac OS.
@JakobEngel I could create a pull request for this code although it is not a big change.

**Comment by JakobEngel** [comment]
should be fixed. can you confirm & close the issue?
@lukasvst  @hlzz 
thanks!

**Comment by hlzz** [comment]
Yes. The program can run for now. But it would still crash when any of the following three options are checked:

showFramesWindow
showFullTracking
showCoarseTracking

Here is the log message for your reference:

> Reading Photometric Calibration from file /Users/STW/Downloads/sequence_38/pcalib.txt
> Reading Vignette Image from /Users/STW/Downloads/sequence_38/vignette.png
> Successfully read photometric calibration!
> got 3330 images and 3330 timestamps and 3330 exposures.!
> ImageFolderReader: got 3330 files in /Users/STW/Downloads/sequence_38/images!
> using pyramid levels 0 to 3. coarsest resolution: 80 x 60!
> START PANGOLIN!
> Initialization: keep 21.7% (need 2000, have 9205)!
> INITIALIZE FROM INITIALIZER (1995 pts)!
> SPARSITY:  MinActDist 1.900000 (need 2000 points, have 1995 points)!
> OPTIMIZE 1995 pts, 1995 active res, 0 lin res!
> Initial Error       	A(271220.825474)=(AV inf). Num: A(0) + M(0); ab 0.000000 0.000000!
> STEPS: A 0.0; B 4.8; R 3.7; T 19.4. 	ACCEPT 0 (L -1.00, dir nan, ss 1.0): 	A(220350.908493)=(AV 4.517). Num: A(1350) + M(0); ab -0.000023 -0.408337!
> STEPS: A 0.0; B 0.8; R 5.5; T 16.6. 	ACCEPT 1 (L -1.60, dir -0.10, ss 1.0): A(193502.530315)=(AV 4.124). Num: A(1422) + M(0); ab -0.000026 -0.474465!
> STEPS: A 0.0; B 0.3; R 4.9; T 13.2. 	ACCEPT 2 (L -2.20, dir 0.65, ss 1.0): 	A(190411.950635)=(AV 4.098). Num: A(1417) + M(0); ab -0.000026 -0.495699!
> STEPS: A 0.0; B 0.1; R 3.9; T 9.8. 	ACCEPT 3 (L -2.81, dir 0.98, ss 1.0): 	A(188954.762744)=(AV 4.086). Num: A(1415) + M(0); ab -0.000027 -0.501420!
> STEPS: A 0.0; B 0.1; R 2.7; T 6.4. 	ACCEPT 4 (L -3.41, dir 1.00, ss 1.0): 	A(188508.451043)=(AV 4.079). Num: A(1416) + M(0); ab -0.000027 -0.508361!
> STEPS: A 0.0; B 0.0; R 2.1; T 4.6. 	ACCEPT 5 (L -4.01, dir 0.98, ss 1.0): 	A(188267.492799)=(AV 4.075). Num: A(1417) + M(0); ab -0.000027 -0.508090!
> STEPS: A 0.0; B 0.0; R 1.5; T 3.1. 	ACCEPT 6 (L -4.61, dir 1.00, ss 1.0): 	A(188231.477409)=(AV 4.073). Num: A(1418) + M(0); ab -0.000027 -0.510085!
> STEPS: A 0.0; B 0.0; R 1.1; T 2.2. 	REJECT 7 (L -5.21, dir 0.98, ss 1.0): 	A(188270.271836)=(AV 4.074). Num: A(1418) + M(0); ab -0.000027 -0.508798!
> STEPS: A 0.0; B 0.0; R 0.8; T 1.4. 	REJECT 8 (L -5.82, dir 0.99, ss 1.0): 	A(188765.669262)=(AV 4.079). Num: A(1418) + M(0); ab -0.000027 -0.511647!
> STEPS: A 0.0; B 0.1; R 1.4; T 3.6. 	ACCEPT 9 (L -6.42, dir 0.99, ss 1.0): 	A(188246.814878)=(AV 4.076). Num: A(1416) + M(0); ab -0.000027 -0.505482!
> STEPS: A 0.0; B 0.0; R 2.6; T 6.7. 	ACCEPT 10 (L -7.02, dir 1.00, ss 1.0): A(188207.493248)=(AV 4.076). Num: A(1416) + M(0); ab -0.000027 -0.504278!
> STEPS: A 0.0; B 0.0; R 1.6; T 3.9. 	REJECT 11 (L -7.62, dir 0.99, ss 1.0): A(188243.277633)=(AV 4.076). Num: A(1416) + M(0); ab -0.000027 -0.502517!
> STEPS: A 0.0; B 0.0; R 1.2; T 2.7. 	REJECT 12 (L -8.22, dir 1.00, ss 1.0): A(188780.399215)=(AV 4.082). Num: A(1416) + M(0); ab -0.000027 -0.506729!
> STEPS: A 0.0; B 0.0; R 1.0; T 2.2. 	REJECT 13 (L -8.83, dir 0.99, ss 1.0): A(188911.018883)=(AV 4.085). Num: A(1415) + M(0); ab -0.000027 -0.505038!
> STEPS: A 0.0; B 0.0; R 0.7; T 1.4. 	REJECT 14 (L -9.43, dir 0.99, ss 1.0): A(189023.176217)=(AV 4.086). Num: A(1415) + M(0); ab -0.000027 -0.508112!
> LOG 9: 4.086 fine. Res: 1415 A, 0 L, 0 M; (0 / 0) forceDrop. a=-0.000027, b=-0.508112. Window 9 (2)
> Coarse Tracker tracked ab = -0.014762 0.641270 (exp 10.081544). Res 2.825979!
> Coarse Tracker tracked ab = -0.010591 0.181534 (exp 10.081544). Res 3.435972!
> Coarse Tracker tracked ab = -0.010527 0.026119 (exp 10.081544). Res 4.082731!
> Coarse Tracker tracked ab = -0.007131 -0.388757 (exp 10.081544). Res 4.996680!
> Coarse Tracker tracked ab = -0.013262 0.021158 (exp 10.081544). Res 5.626656!
> Coarse Tracker tracked ab = -0.007376 -0.659720 (exp 10.081544). Res 5.857679!
> SPARSITY:  MinActDist 1.400000 (need 2000 points, have 1415 points)!
> OPTIMIZE 2013 pts, 4019 active res, 0 lin res!
> Initial Error       	A(476832.231487)=(AV 6.490). Num: A(1415) + M(0); ab -0.007376 -0.659720!
> STEPS: A 0.7; B 2.2; R 73.5; T 178.9. 	ACCEPT 0 (L -1.00, dir nan, ss 1.0): 	A(401941.328279)=(AV 3.672). Num: A(3727) + M(0); ab -0.000018 -0.863199!
> STEPS: A 0.0; B 0.2; R 49.1; T 109.2. 	ACCEPT 1 (L -1.60, dir 0.98, ss 1.0): 	A(362523.389061)=(AV 3.456). Num: A(3794) + M(0); ab -0.000021 -0.875217!
> STEPS: A 0.0; B 0.2; R 23.0; T 46.9. 	ACCEPT 2 (L -2.20, dir 0.65, ss 1.0): 	A(343117.786523)=(AV 3.342). Num: A(3840) + M(0); ab -0.000022 -0.859619!
> STEPS: A 0.0; B 0.1; R 15.1; T 30.1. 	ACCEPT 3 (L -2.81, dir 0.98, ss 1.0): 	A(329160.044208)=(AV 3.264). Num: A(3862) + M(0); ab -0.000023 -0.860462!
> STEPS: A 0.0; B 0.0; R 7.9; T 16.9. 	ACCEPT 4 (L -3.41, dir 0.95, ss 1.0): 	A(325341.854631)=(AV 3.242). Num: A(3869) + M(0); ab -0.000023 -0.857959!
> STEPS: A 0.0; B 0.2; R 4.4; T 7.3. 	ACCEPT 5 (L -4.01, dir 0.95, ss 1.0): 	A(323834.383859)=(AV 3.234). Num: A(3870) + M(0); ab -0.000024 -0.876311!
> STEPS: A 0.0; B 0.0; R 2.0; T 5.6. 	REJECT 6 (L -4.61, dir 0.70, ss 1.0): 	A(326344.160153)=(AV 3.247). Num: A(3870) + M(0); ab -0.000023 -0.876753!
> STEPS: A 0.0; B 0.1; R 0.8; T 1.2. 	REJECT 7 (L -5.21, dir -0.56, ss 1.0): A(326544.014679)=(AV 3.248). Num: A(3868) + M(0); ab -0.000024 -0.891243!
> STEPS: A 0.0; B 0.1; R 0.9; T 2.5. 	REJECT 8 (L -5.82, dir -0.52, ss 1.0): A(328701.510005)=(AV 3.260). Num: A(3865) + M(0); ab -0.000024 -0.885613!
> STEPS: A 0.0; B 0.0; R 0.5; T 1.6. 	REJECT 9 (L -6.42, dir -0.99, ss 1.0): A(330063.102022)=(AV 3.266). Num: A(3868) + M(0); ab -0.000024 -0.886570!
> STEPS: A 0.0; B 0.1; R 1.0; T 1.6. 	REJECT 10 (L -7.02, dir -0.28, ss 1.0):A(332409.689859)=(AV 3.281). Num: A(3859) + M(0); ab -0.000024 -0.890219!
> STEPS: A 0.0; B 0.1; R 1.2; T 1.9. 	REJECT 11 (L -7.62, dir -0.96, ss 1.0):A(334891.378149)=(AV 3.293). Num: A(3860) + M(0); ab -0.000024 -0.881084!
> STEPS: A 0.0; B 0.2; R 1.3; T 1.6. 	REJECT 12 (L -8.22, dir -0.91, ss 1.0):A(335644.617082)=(AV 3.300). Num: A(3853) + M(0); ab -0.000024 -0.896789!
> STEPS: A 0.0; B 0.2; R 0.7; T 1.7. 	REJECT 13 (L -8.83, dir -0.48, ss 1.0):A(337291.655386)=(AV 3.306). Num: A(3857) + M(0); ab -0.000023 -0.879587!
> STEPS: A 0.0; B 0.1; R 0.7; T 1.0. 	REJECT 14 (L -9.43, dir -0.62, ss 1.0):A(337764.137156)=(AV 3.311). Num: A(3852) + M(0); ab -0.000024 -0.892396!
> LOG 15: 3.311 fine. Res: 3852 A, 0 L, 0 M; (0 / 0) forceDrop. a=-0.000024, b=-0.892396. Window 15 (3)
> Coarse Tracker tracked ab = -0.018786 0.394011 (exp 10.081544). Res 2.514235!
> Coarse Tracker tracked ab = -0.025025 0.931106 (exp 10.081544). Res 3.126558!
> Coarse Tracker tracked ab = -0.025073 0.938177 (exp 10.081544). Res 3.130955!
> Coarse Tracker tracked ab = -0.023338 0.605236 (exp 10.081544). Res 3.154930!
> Coarse Tracker tracked ab = -0.033413 1.302696 (exp 10.081544). Res 4.073624!
> SPARSITY:  MinActDist 1.300000 (need 2000 points, have 1966 points)!
> OPTIMIZE 2745 pts, 8108 active res, 0 lin res!
> Initial Error       	A(742329.328229)=(AV 4.908). Num: A(3852) + M(0); ab -0.033413 1.302696!
> STEPS: A 2.8; B 18.7; R 62.2; T 150.1. 	ACCEPT 0 (L -1.00, dir nan, ss 1.0): 	A(699935.001784)=(AV 3.346). Num: A(7815) + M(0); ab -0.000053 -0.944828!
> STEPS: A 0.0; B 0.1; R 7.0; T 14.8. 	ACCEPT 1 (L -1.60, dir 0.82, ss 1.0): 	A(689455.563084)=(AV 3.324). Num: A(7801) + M(0); ab -0.000052 -0.953167!
> STEPS: A 0.0; B 0.1; R 2.2; T 4.1. 	ACCEPT 2 (L -2.20, dir 0.50, ss 1.0): 	A(687835.466227)=(AV 3.323). Num: A(7788) + M(0); ab -0.000050 -0.955389!
> STEPS: A 0.0; B 0.0; R 0.7; T 1.4. 	ACCEPT 3 (L -2.81, dir 0.10, ss 1.0): 	A(685592.845531)=(AV 3.318). Num: A(7785) + M(0); ab -0.000050 -0.950431!
> STEPS: A 0.0; B 0.0; R 0.8; T 1.3. 	ACCEPT 4 (L -3.41, dir -0.39, ss 1.0): A(685533.741629)=(AV 3.317). Num: A(7788) + M(0); ab -0.000050 -0.954703!
> STEPS: A 0.0; B 0.1; R 0.6; T 1.6. 	ACCEPT 5 (L -4.01, dir 0.53, ss 1.0): 	A(684841.355723)=(AV 3.316). Num: A(7785) + M(0); ab -0.000050 -0.948008!
> LOG 20: 3.316 fine. Res: 7785 A, 0 L, 0 M; (0 / 0) forceDrop. a=-0.000050, b=-0.948008. Window 20 (4)
> Coarse Tracker tracked ab = -0.016396 0.305619 (exp 10.081544). Res 3.050882!
> Coarse Tracker tracked ab = -0.012411 0.129818 (exp 10.081544). Res 2.314183!
> Coarse Tracker tracked ab = -0.011475 -0.191261 (exp 10.081544). Res 2.838339!
> Coarse Tracker tracked ab = -0.008146 -0.227700 (exp 10.081544). Res 3.546989!
> Coarse Tracker tracked ab = -0.012733 0.202958 (exp 10.040421). Res 3.095646!
> SPARSITY:  MinActDist 2.100000 (need 2000 points, have 2650 points)!
> OPTIMIZE 2830 pts, 10803 active res, 0 lin res!
> Initial Error       	A(955110.297365)=(AV 3.916). Num: A(7785) + M(0); ab -0.012733 0.202958!
> STEPS: A 0.9; B 6.8; R 13.2; T 29.6. 	ACCEPT 0 (L -1.00, dir nan, ss 1.0): 	A(925257.432301)=(AV 3.326). Num: A(10455) + M(0); ab -0.000046 -0.708182!
> STEPS: A 0.0; B 0.2; R 1.0; T 2.6. 	ACCEPT 1 (L -1.60, dir 0.69, ss 1.0): 	A(918756.552071)=(AV 3.315). Num: A(10450) + M(0); ab -0.000047 -0.691739!
> STEPS: A 0.0; B 0.0; R 0.9; T 1.3. 	REJECT 2 (L -2.20, dir 0.01, ss 1.0): 	A(919761.674658)=(AV 3.318). Num: A(10446) + M(0); ab -0.000047 -0.697103!
> STEPS: A 0.0; B 0.0; R 0.3; T 0.5. 	ACCEPT 3 (L -2.81, dir -0.81, ss 1.0): A(919253.957400)=(AV 3.317). Num: A(10444) + M(0); ab -0.000047 -0.690905!
> LOG 25: 3.317 fine. Res: 10444 A, 0 L, 324 M; (0 / 0) forceDrop. a=-0.000047, b=-0.690905. Window 25 (5)
> Coarse Tracker tracked ab = -0.005523 -0.440577 (exp 10.040421). Res 2.029320!
> Coarse Tracker tracked ab = -0.011634 -0.143263 (exp 10.040421). Res 2.631047!
> Coarse Tracker tracked ab = -0.032669 1.596830 (exp 10.040421). Res 3.040525!
> Coarse Tracker tracked ab = -0.001939 0.564145 (exp 9.872281). Res 2.658994!
> SPARSITY:  MinActDist 2.900000 (need 2000 points, have 2630 points)!
> OPTIMIZE 2774 pts, 12938 active res, 0 lin res!
> Initial Error       	A(1107327.339549)=(AV 3.640). Num: A(10444) + M(324); ab -0.001939 0.564145!
> STEPS: A 0.1; B 2.3; R 3.4; T 9.0. 	ACCEPT 0 (L -1.00, dir nan, ss 1.0): 	A(1075104.008100)=(AV 3.269). Num: A(12575) + M(324); ab -0.000018 0.231890!
> STEPS: A 0.0; B 0.1; R 0.7; T 2.4. 	ACCEPT 1 (L -1.60, dir 0.02, ss 1.0): 	A(1071055.958390)=(AV 3.264). Num: A(12563) + M(324); ab -0.000019 0.247764!
> STEPS: A 0.0; B 0.1; R 0.3; T 0.5. 	ACCEPT 2 (L -2.20, dir -0.00, ss 1.0): A(1068973.205121)=(AV 3.262). Num: A(12561) + M(324); ab -0.000019 0.229526!
> LOG 29: 3.261 fine. Res: 12561 A, 0 L, 1140 M; (0 / 0) forceDrop. a=-0.000019, b=0.229526. Window 29 (6)
> Coarse Tracker tracked ab = -0.029197 1.847712 (exp 9.872281). Res 2.266589!
> Coarse Tracker tracked ab = -0.035330 2.284110 (exp 9.872281). Res 2.401265!
> Coarse Tracker tracked ab = -0.020746 1.333282 (exp 9.872281). Res 2.277791!
> Coarse Tracker tracked ab = -0.021143 1.380417 (exp 9.872281). Res 2.331208!
> SPARSITY:  MinActDist 3.200000 (need 2000 points, have 2540 points)!
> OPTIMIZE 2720 pts, 14699 active res, 0 lin res!
> Initial Error       	A(1247380.626320)=(AV 3.523). Num: A(12561) + M(1140); ab -0.021143 1.380417!
> STEPS: A 1.3; B 10.1; R 2.3; T 5.3. 	ACCEPT 0 (L -1.00, dir nan, ss 1.0): 	A(1221510.335734)=(AV 3.255). Num: A(14413) + M(1140); ab -0.000027 -0.218034!
> STEPS: A 0.0; B 0.1; R 0.2; T 0.6. 	ACCEPT 1 (L -1.60, dir 0.09, ss 1.0): 	A(1219102.041124)=(AV 3.253). Num: A(14397) + M(1140); ab -0.000027 -0.216131!
> 2016-11-22 22:19:59.684 dso_dataset[76670:4733393] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'nextEventMatchingMask should only be called from the Main Thread!'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007fffc56316fb __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x00007fffd9e38a2a objc_exception_throw + 48
> 	2   AppKit                              0x00007fffc394450c -[NSApplication(NSEvent) shouldBeTreatedAsInkEvent:] + 0
> 	3   libopencv_highgui.2.4.dylib         0x00000001088e10a6 cvWaitKey + 402
> 	4   dso_dataset                         0x0000000106783afc _ZN3dso6IOWrap7waitKeyEi + 60
> 	5   dso_dataset                         0x0000000106722805 _ZN3dso10FullSystem9debugPlotENSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 6837
> 	6   dso_dataset                         0x00000001066efd32 _ZN3dso10FullSystem12makeKeyFrameEPNS_12FrameHessianE + 2194
> 	7   dso_dataset                         0x00000001066ef20e _ZN3dso10FullSystem19deliverTrackedFrameEPNS_12FrameHessianEb + 110
> 	8   dso_dataset                         0x00000001066eddc7 _ZN3dso10FullSystem14addActiveFrameEPNS_16ImageAndExposureEi + 1623
> 	9   dso_dataset                         0x00000001066e0f42 _ZNSt3__114__thread_proxyINS_5tupleIJZ4mainE3$_0EEEEEPvS4_ + 1282
> 	10  libsystem_pthread.dylib             0x00007fffda92caab _pthread_body + 180
> 	11  libsystem_pthread.dylib             0x00007fffda92c9f7 _pthread_body + 0
> 	12  libsystem_pthread.dylib             0x00007fffda92c221 thread_start + 13
> )
> libc++abi.dylib: terminating with uncaught exception of type NSException
> Abort trap: 6
>

**Comment by JakobEngel** [comment]
Great! Yes, that is somewhat expected, since those options create additional, openCV-based display windows and really are only left-overs from when I was using OpenCV for visualization.
It's unlikely I'll fix that - just don't use the buttons, they are only for debugging anyway ;).

If I find the time, I may integrate that functionality (which essentially visualize the residual image for initial direct image alignment, the color-coded points across their respective keypoints, and all projected points across all keyframes in many windows) into the Pangolin based viewer - which will fix this issue.
